defaults: &defaults
  adapter: postgresql
  database: countries_pallete
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *defaults
  database: countries_pallete_test
  pool: 8

development:
  <<: *defaults

production:
  <<: *defaults
